apache/sling-org-apache-sling-feature-cpconverter

pom.xml

The maven-assembly-plugin configuration was overridden globally rather
than added for an extra goal

SLING-8979 Include the -source-release.zip file in releases

---

src/main/java/org/apache/sling/feature/cpconverter/cli/ContentPackage2FeatureModelConverterLauncher.java
src/main/java/org/apache/sling/feature/cpconverter/cli/ShutDownHook.java
src/main/java/org/apache/sling/feature/cpconverter/vltpkg/VaultPackageAssembler.java
src/test/java/org/apache/sling/feature/cpconverter/vltpkg/VaultPackageAssemblerTest.java

added cleanup method to cleanup directories that the converter create. 
FYI @DominikSuess

Feature Converter doesn't cleanup after itself

---

pom.xml

Mark the org.osgi.util.function package as 'provided', to make sure it ends up
in the assembly. The dependency scope was either an accident, or a leftover
from when the configadmin did not require org.osgi.util.function.

SLING-9728 - Conversion fails for JSON configurations with type conversions: ClassNotFoundException: org.osgi.util.function.Function

---

pom.xml
src/main/java/org/apache/sling/feature/cpconverter/cli/ContentPackage2FeatureModelConverterLauncher.java
src/main/java/org/apache/sling/feature/cpconverter/features/DefaultFeaturesManager.java
src/main/java/org/apache/sling/feature/cpconverter/features/FeaturesManager.java
src/main/java/org/apache/sling/feature/cpconverter/handlers/BundleEntryHandler.java
src/test/java/org/apache/sling/feature/cpconverter/ContentPackage2FeatureModelConverterTest.java
src/test/java/org/apache/sling/feature/cpconverter/acl/AclManagerTest.java
src/test/java/org/apache/sling/feature/cpconverter/features/FeaturesManagerTest.java

The region can be specified with the -e / --exports-to-region option.
Normally when this option is used the region specified with this option
would be the 'global' region or a region specific to the content
package.

SLING-9827 Specify the API Region to export packages into

---

src/main/java/org/apache/sling/feature/cpconverter/accesscontrol/DefaultAclManager.java
src/main/java/org/apache/sling/feature/cpconverter/handlers/RepPolicyEntryHandler.java
src/main/java/org/apache/sling/feature/cpconverter/handlers/RepRepoPolicyEntryHandler.java
src/main/java/org/apache/sling/feature/cpconverter/shared/RepoPath.java
src/main/resources/META-INF/services/org.apache.sling.feature.cpconverter.handlers.EntryHandler
src/test/java/org/apache/sling/feature/cpconverter/ContentPackage2FeatureModelConverterTest.java
src/test/java/org/apache/sling/feature/cpconverter/handlers/RepRepoPolicyEntryHandlerTest.java
src/test/java/org/apache/sling/feature/cpconverter/handlers/SystemUsersEntryHandlerTest.java
src/test/java/org/apache/sling/feature/cpconverter/handlers/TestUtils.java
src/test/resources/org/apache/sling/feature/cpconverter/handlers/jcr_root/_rep_repoPolicy.xml

@karlpauls , a few notes/questions regarding this PR (copied from jira):
- the regex in the new RepRepoPolicyEntryHandler looks a rather ugly to me.... if you have a better idea on how to do this without changing too much of the logic in RepPolicyEntryHandler, please let me know. in Oak the rep:repoPolicy can only occur at the root node but the call to `matcher.group(1)` in AbstractPolicyParser forces a group in the regex
- RepoPath: should isRepositoryPath be reflected in the equals/hashcode methods?
- DefaultAclManager: the method getRepoInitPath introduced in the patch has a param SystemUser which is not used yet.... but will it be needed for SLING-9692 and SLING-9953. since i derived the patch from some initial work done for those issues i decided to leave it in.
- TestUtils: i …

SLING-9956 : RepPolicyEntryHandler ignores ACEs on repository level

---

src/main/java/org/apache/sling/feature/cpconverter/accesscontrol/AclManager.java
src/main/java/org/apache/sling/feature/cpconverter/accesscontrol/DefaultAclManager.java
src/main/java/org/apache/sling/feature/cpconverter/accesscontrol/Mapping.java
src/main/java/org/apache/sling/feature/cpconverter/cli/ContentPackage2FeatureModelConverterLauncher.java
src/main/java/org/apache/sling/feature/cpconverter/handlers/AbstractConfigurationEntryHandler.java
src/test/java/org/apache/sling/feature/cpconverter/accesscontrol/EnforcePrincipalBasedTest.java
src/test/java/org/apache/sling/feature/cpconverter/accesscontrol/MappingTest.java
src/test/java/org/apache/sling/feature/cpconverter/handlers/ConfigurationEntryHandlerTest.java
src/test/java/org/apache/sling/feature/cpconverter/handlers/JsonConfigurationEntryHandlerTest.java
src/test/java/org/apache/sling/feature/cpconverter/handlers/TestUtils.java
src/test/resources/org/apache/sling/feature/cpconverter/handlers/jcr_root/apps/asd/config.author/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.config
src/test/resources/org/apache/sling/feature/cpconverter/handlers/jcr_root/apps/asd/config.publish/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.config
src/test/resources/org/apache/sling/feature/cpconverter/handlers/jcr_root/apps/asd/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.cfg
src/test/resources/org/apache/sling/feature/cpconverter/handlers/jcr_root/apps/asd/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.cfg.json
src/test/resources/org/apache/sling/feature/cpconverter/handlers/jcr_root/apps/asd/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.config
src/test/resources/org/apache/sling/feature/cpconverter/handlers/jcr_root/apps/asd/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.config.xml
src/test/resources/org/apache/sling/feature/cpconverter/handlers/jcr_root/apps/asd/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.typed.xml
src/test/resources/org/apache/sling/feature/cpconverter/handlers/jcr_root/apps/asd/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.xml
src/test/resources/org/apache/sling/feature/cpconverter/handlers/jcr_root/apps/asd/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.xml.cfg

@karlpauls , some intial work for SLING-10070. the following pieces are not yet completed, some marked with TODO:
- parsing of *ServiceUserMapperImpl.*.cfg files returns a 'user.mapping' String and not a String array. i don't know if the problem is located with the test-files or if that is valid and needs extra parsing.... currently throws exception and is marked with TODO
- Mapping (and thus the parsing) is copied from sling service-user-mapping... i would prefer to avoid the code duplication if possible
- with the current flow in DefaultAclManager it will iterate multiple times over the mappings. 
- missing tests for those cases where principal-based ac setup cannot be enforced (single user mapping)
- the would default to enforce if there was no mapping defined in the content …

SLING-10070 : Option to enforce principal-based authorization (wip)

---

src/main/java/org/apache/sling/feature/cpconverter/accesscontrol/AbstractUser.java
src/main/java/org/apache/sling/feature/cpconverter/accesscontrol/DefaultAclManager.java
src/main/java/org/apache/sling/feature/cpconverter/accesscontrol/SystemUser.java
src/main/java/org/apache/sling/feature/cpconverter/accesscontrol/User.java
src/main/java/org/apache/sling/feature/cpconverter/handlers/AbstractUserParser.java
src/main/java/org/apache/sling/feature/cpconverter/handlers/GroupEntryHandler.java
src/main/java/org/apache/sling/feature/cpconverter/handlers/UsersEntryHandler.java
src/test/java/org/apache/sling/feature/cpconverter/handlers/UsersEntryHandlerTest.java
src/test/resources/org/apache/sling/feature/cpconverter/handlers/jcr_root/home/users/a/disableduser/.content.xml

@karlpauls , i would appreciate if you had time to take a look at the suggested fix. nothing urgent and it's probably a minor bug but if the converter is expected to work reliably with an increasing number of different content packages that's something that sooner or later will pop up (and potentially cause security issues).

SLING-10286 : Converter ignores disabled status of system user

---

src/main/java/org/apache/sling/feature/cpconverter/accesscontrol/DefaultAclManager.java
src/test/java/org/apache/sling/feature/cpconverter/accesscontrol/AclManagerTest.java
src/test/java/org/apache/sling/feature/cpconverter/accesscontrol/EnforcePrincipalBasedTest.java
src/test/java/org/apache/sling/feature/cpconverter/handlers/RepPolicyEntryHandlerTest.java

@karlpauls , as discussed a proposed fix. note, that no attempt is made to create a path below /home if the type information is missing altogether. the reason for this is the nodetype definition of rep:AuthorizableFolder, which would pick rep:User as the default primary type first (and not rep:AuthorizableFolder) and thus would likely result in a failure during repo-init

SLING-10386 : Converter needs to issue create path statements for repoinit path without node type

---

src/main/java/org/apache/sling/feature/cpconverter/accesscontrol/DefaultAclManager.java
src/main/java/org/apache/sling/feature/cpconverter/shared/RepoPath.java
src/test/java/org/apache/sling/feature/cpconverter/accesscontrol/AclManagerTest.java
src/test/java/org/apache/sling/feature/cpconverter/shared/RepoPathTest.java

@karlpauls , sorry.... didn't notice that you merged the previous commit already... wanted to keep the 2 bugs together as SLING-10386 cannot be fixed IMHO without fixing the RepoPath.

SLING-10388 : RepoPath.getParent returns null for top-level paths

---

src/main/java/org/apache/sling/feature/cpconverter/shared/RepoPath.java

SLING-10388 : RepoPath.getParent returns null for top-level paths (nullability annotations)

---

pom.xml
src/main/assembly/bin.xml

SLING-10401 change scope to 'compile' to not hide dependencies for

---

src/main/java/org/apache/sling/feature/cpconverter/ContentPackage2FeatureModelConverter.java
src/main/java/org/apache/sling/feature/cpconverter/vltpkg/VaultPackageAssembler.java
src/test/java/org/apache/sling/feature/cpconverter/ConverterUserAndPermissionTest.java

@karlpauls , expanded the ConverterUserAndPermissionTest to illustrate the issue described in the ticket (test failes)

SLING-10467 : Converted content package referres to paths moved to repo-init

---

src/main/java/org/apache/sling/feature/cpconverter/ContentPackage2FeatureModelConverter.java
src/main/java/org/apache/sling/feature/cpconverter/handlers/DefaultHandler.java
src/main/java/org/apache/sling/feature/cpconverter/vltpkg/VaultPackageAssembler.java
src/test/java/org/apache/sling/feature/cpconverter/handlers/DefaultHandlerTest.java
src/test/java/org/apache/sling/feature/cpconverter/vltpkg/VaultPackageAssemblerTest.java

@karlpauls , let me know if you think that is rather unnecessary or confusing. to me VaultPackageAssembler implementing EntryHandler looks odd.... but it might just be me.

SLING-10769 : VaultPackageAssembler should not implement EntryHandler

---

src/main/java/org/apache/sling/feature/cpconverter/accesscontrol/DefaultAclManager.java

@karlpauls , i would appreciate if you had time to take a look. after refactoring the method `getCreatePath` to reduce it's complexity it struck me that the separate if for RepoPath.getParent being null is only executed at the very end. imho that should go first as computing the "CreatePath" statement doesn't impact the original RepoPath param, does it?

SLING-10786 : DefaultAclManager - sonar finding

---

src/main/java/org/apache/sling/feature/cpconverter/handlers/XmlConfigurationEntryHandler.java

hi @karlpauls improving XmlConfigurationEntryHandler required a bit of refactoring. i would appreciate if you could take a look.
note: originally the switch-case contained non-null checks for all property types but that got removed with SLING-10329 : Remove dependency to Plexus StringUtils, which left the different cases in an inconsistent state (at least i kept wondering why some are checking for null, some only checking for empty string). it tried to fix that as well.

SLING-10783 : XmlConfigurationEntryHandler - sonar findings

---

src/main/java/org/apache/sling/feature/cpconverter/ContentPackage2FeatureModelConverter.java

https://issues.apache.org/jira/browse/SLING-10929
From : 
To:
:

SLING-10929 : Wrap the exceptions of onFile an provide a path to the output

---

src/main/java/org/apache/sling/feature/cpconverter/index/IndexDefinitionsJsonWriter.java
src/test/java/org/apache/sling/feature/cpconverter/index/IndexDefinitionsJsonWriterTest.java

Tolerate long values that end with '.0', the intent is clearly for them to be valid longs.

SLING-11240 - Content packages with invalid Long properties cause index definition extraction to fail

---

src/main/java/org/apache/sling/feature/cpconverter/handlers/IndexDefinitionsEntryHandler.java
src/main/java/org/apache/sling/feature/cpconverter/index/SimpleNamespaceResolver.java
src/test/java/org/apache/sling/feature/cpconverter/handlers/IndexDefinitionsEntryHandlerTest.java
src/test/java/org/apache/sling/feature/cpconverter/index/IndexDefinitionsJsonWriterTest.java
src/test/resources/org/apache/sling/feature/cpconverter/handlers/index/index_missing_namespaces/META-INF/vault/filter.xml
src/test/resources/org/apache/sling/feature/cpconverter/handlers/index/index_missing_namespaces/META-INF/vault/nodetypes.cnd
src/test/resources/org/apache/sling/feature/cpconverter/handlers/index/index_missing_namespaces/META-INF/vault/properties.xml
src/test/resources/org/apache/sling/feature/cpconverter/handlers/index/index_missing_namespaces/jcr_root/.content.xml
src/test/resources/org/apache/sling/feature/cpconverter/handlers/index/index_missing_namespaces/jcr_root/_oak_index/.content.xml

Introduce a NamespaceResolver that is aware of the default Oak namespace URI and prefix.

SLING-11241 - Content package with index definitions missing the Oak namespace causes index extraction to fail

---

src/main/java/org/apache/sling/feature/cpconverter/accesscontrol/DefaultAclManager.java
src/main/java/org/apache/sling/feature/cpconverter/accesscontrol/EnforceInfo.java
src/main/java/org/apache/sling/feature/cpconverter/cli/ContentPackage2FeatureModelConverterLauncher.java
src/main/java/org/apache/sling/feature/cpconverter/repoinit/SystemUserVisitor.java
src/main/java/org/apache/sling/feature/cpconverter/shared/ConverterConstants.java
src/test/java/org/apache/sling/feature/cpconverter/ConverterUserAndPermissionTest.java
src/test/java/org/apache/sling/feature/cpconverter/Util.java
src/test/java/org/apache/sling/feature/cpconverter/accesscontrol/AclManagerTest.java
src/test/java/org/apache/sling/feature/cpconverter/accesscontrol/EnforceInfoTest.java
src/test/java/org/apache/sling/feature/cpconverter/accesscontrol/EnforcePrincipalBasedTest.java
src/test/java/org/apache/sling/feature/cpconverter/handlers/RepoInitTest.java

@karlpauls and @niekraaijmakers i would very much appreciate if you could review my PR.

SLING-11663 : Create all service users with forced path

---

src/main/java/org/apache/sling/feature/cpconverter/handlers/IndexDefinitionsEntryHandler.java
src/test/java/org/apache/sling/feature/cpconverter/handlers/IndexDefinitionsEntryHandlerTest.java

Change the indexdefinitionshandler to include everything under oak index, except for a blacklist of files

SLING-11675 - Index definition extraction from content packages is missing non-XML files

---

src/main/java/org/apache/sling/feature/cpconverter/index/IndexDefinitionsJsonWriter.java
src/test/java/org/apache/sling/feature/cpconverter/index/IndexDefinitionsJsonWriterTest.java

Avoid setting the 'str:' prefix unless necessary.

SLING-11837 - Align index definition generation logic with the one from Oak

---

pom.xml
src/main/java/org/apache/sling/feature/cpconverter/repoinit/DefaultVisitor.java
src/main/java/org/apache/sling/feature/cpconverter/repoinit/NoOpVisitor.java
src/test/resources/org/apache/sling/feature/cpconverter/handlers/jcr_root/apps/asd/config.publish/org.apache.sling.jcr.repoinit.RepositoryInitializer-no-conversion-result.config
src/test/resources/org/apache/sling/feature/cpconverter/handlers/jcr_root/apps/asd/config.publish/org.apache.sling.jcr.repoinit.RepositoryInitializer-no-conversion-test.config

hi @rombert and @kwin , while searching for tickets related to sling-initial-content in jira, i stumbled across this one here. IMHO none of the new repo-init statements requires any conversion and thus they can be written out in their original form (similar to CreatePath and SetAclPrincipalBased).
i would still appreciate if you could take a careful look. thank you!

SLING-11750 : Support the new repoinit statements

---

src/main/java/org/apache/sling/feature/cpconverter/handlers/slinginitialcontent/SlingInitialContentBundleEntryMetaDataCollector.java

https://issues.apache.org/jira/browse/SLING-12113

SLING-12113 CPConverter: Improve error message "File being unzipped is too big" for Sling-Initial-Content
